/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package departmentalstore;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author walee_000
 */
public class EmployeeForm extends javax.swing.JFrame {
    String Name,Fname,cinc,contact,gender,bdate,hdate,bgroup,address,domicile,password,salary,path;
    ResultSet rs;
    Connection cn;
    PreparedStatement pst;
    Statement st;

    /**
     * Creates new form EmployeeForm
     */
    public EmployeeForm() {
        initComponents();
        try
        {
            
        
        Class.forName("com.mysql.jdbc.Driver").newInstance();
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/departmental_store","root","");
        }
        catch(Exception e)
        {
          System.out.println(e);  
        }
    }
        private DefaultTableModel rtt(ResultSet rs){
    try{
            DefaultTableModel dtm = new DefaultTableModel();
            ResultSetMetaData meta = rs.getMetaData();
            int col = meta.getColumnCount();
 
            rs.last();
            int row = rs.getRow();
            rs.beforeFirst();
 
            Object[] rowData = new Object[col];
            Object[] colData = new Object[col];
 
            for (int i=0;i<col;i++){
                colData[i] = meta.getColumnLabel(i+1);
            }
 
            dtm.setColumnIdentifiers(colData);
 
            for (int i=0;i<row;i++){
                rs.next();
                for (int j=0;j<col;j++){
                    rowData[j] = rs.getString(j+1);
                }
                dtm.addRow(rowData);
            }
 
            return dtm;
    } catch (Exception ex){
        JOptionPane.showMessageDialog(null, "ResultSet to TableModel Converter : "+ex.getMessage());
        return null;
    }
          }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        tffname = new javax.swing.JTextField();
        tfcnic = new javax.swing.JTextField();
        tfcontact = new javax.swing.JTextField();
        tfadress = new javax.swing.JTextField();
        tfpassword = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfdomicile = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfbgroup = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfsalary = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        rmalee = new javax.swing.JRadioButton();
        rfemale = new javax.swing.JRadioButton();
        tfimage = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        showtable = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbsave = new javax.swing.JButton();
        jbupdate = new javax.swing.JButton();
        jbdelete = new javax.swing.JButton();
        tfupdate = new javax.swing.JTextField();
        limage = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jp = new javax.swing.JProgressBar();
        jdatebd = new com.toedter.calendar.JDateChooser();
        jdatehd = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel2.setText("Father's Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 64, -1, -1));

        jLabel3.setText("CNIC#:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 111, -1, -1));

        jLabel4.setText("Contact#:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 161, -1, -1));

        jLabel5.setText("Password:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 485, -1, -1));

        jLabel6.setText("Address:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 393, -1, -1));

        tfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnameActionPerformed(evt);
            }
        });
        tfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfnameKeyTyped(evt);
            }
        });
        getContentPane().add(tfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 11, 248, -1));

        tffname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tffnameActionPerformed(evt);
            }
        });
        tffname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tffnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tffnameKeyTyped(evt);
            }
        });
        getContentPane().add(tffname, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 58, 248, -1));

        tfcnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcnicActionPerformed(evt);
            }
        });
        tfcnic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfcnicKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfcnicKeyTyped(evt);
            }
        });
        getContentPane().add(tfcnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 108, 248, -1));

        tfcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcontactActionPerformed(evt);
            }
        });
        tfcontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfcontactKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfcontactKeyTyped(evt);
            }
        });
        getContentPane().add(tfcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 155, 248, -1));

        tfadress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfadressActionPerformed(evt);
            }
        });
        tfadress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfadressKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfadressKeyTyped(evt);
            }
        });
        getContentPane().add(tfadress, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 387, 248, -1));

        tfpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpasswordActionPerformed(evt);
            }
        });
        tfpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfpasswordKeyReleased(evt);
            }
        });
        getContentPane().add(tfpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 479, 248, -1));

        jLabel7.setText("Date of Birth:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 235, -1, -1));

        jLabel11.setText("Domicile:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 294, -1, -1));

        tfdomicile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdomicileActionPerformed(evt);
            }
        });
        tfdomicile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfdomicileKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdomicileKeyTyped(evt);
            }
        });
        getContentPane().add(tfdomicile, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 291, 248, -1));

        jLabel12.setText("Blood Group:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 343, -1, -1));

        tfbgroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfbgroupActionPerformed(evt);
            }
        });
        tfbgroup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfbgroupKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfbgroupKeyTyped(evt);
            }
        });
        getContentPane().add(tfbgroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 337, 248, -1));

        jLabel13.setText("Hiring Date:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 439, -1, -1));

        jLabel14.setText("Salary:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 532, -1, -1));

        tfsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsalaryActionPerformed(evt);
            }
        });
        tfsalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfsalaryKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfsalaryKeyTyped(evt);
            }
        });
        getContentPane().add(tfsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 526, 248, -1));

        jLabel15.setText("Gender:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 204, -1, -1));

        buttonGroup1.add(rmalee);
        rmalee.setText("Male");
        rmalee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rmaleeMouseClicked(evt);
            }
        });
        rmalee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmaleeActionPerformed(evt);
            }
        });
        getContentPane().add(rmalee, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 200, -1, -1));

        buttonGroup1.add(rfemale);
        rfemale.setText("Female");
        rfemale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rfemaleMouseClicked(evt);
            }
        });
        rfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfemaleActionPerformed(evt);
            }
        });
        getContentPane().add(rfemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 197, -1, -1));
        getContentPane().add(tfimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1008, 244, 243, -1));

        jButton1.setText("Attach");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton1KeyReleased(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1171, 212, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 51));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "N", "FN", "C", "C#", "G", "Bd", "Hd", "Bg", "A", "D", "P", "S"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        showtable.setViewportView(jTable1);

        jbsave.setText("Save");
        jbsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsaveActionPerformed(evt);
            }
        });

        jbupdate.setText("Update");
        jbupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbupdateActionPerformed(evt);
            }
        });

        jbdelete.setText("Delete");
        jbdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showtable, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jbsave)
                .addGap(33, 33, 33)
                .addComponent(jbupdate)
                .addGap(29, 29, 29)
                .addComponent(jbdelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showtable, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbsave)
                    .addComponent(jbupdate)
                    .addComponent(jbdelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 275, 892, -1));

        tfupdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfupdateKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfupdateKeyTyped(evt);
            }
        });
        getContentPane().add(tfupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 74, 182, 28));

        limage.setText("Attach an image");
        limage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(limage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1028, 11, 223, 171));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Please Enter Employee ID:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, -1, -1));
        getContentPane().add(jp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 1161, -1));

        jdatebd.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jdatebd, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 235, 248, -1));

        jdatehd.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jdatehd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 439, 248, -1));

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1260, 630));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("Close");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Main Page");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Edit");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        jMenuItem3.setText("Delete");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private BufferedImage ThisIsANameOfFun(JLabel label, String address) throws IOException {
       
            BufferedImage buffer = new BufferedImage(label.getWidth(), label.getHeight(), BufferedImage.TYPE_INT_ARGB);
            Graphics2D g = buffer.createGraphics();          
            Image img = ImageIO.read(new File(address));           
            g.drawImage(img, 0, 0, label.getWidth(), label.getHeight(), null);           
            g.dispose();      
        return buffer;
    }
    private void jbsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsaveActionPerformed
        // TODO add your handling code here
        Name=tfname.getText();
        Fname=tffname.getText();
        address=tfadress.getText();
        domicile=tfdomicile.getText();
        contact=tfcontact.getText();
        password=tfpassword.getText();
        salary=tfsalary.getText();
        bgroup=tfbgroup.getText();
        cinc=tfcnic.getText();
        hdate=((JTextField)jdatehd.getDateEditor().getUiComponent()).getText();
        
        bdate= ((JTextField)jdatebd.getDateEditor().getUiComponent()).getText();
        try
        {
            
            
            String sql="INSERT INTO `employee`(`Name`, `E_Password`, `Gender`, `Contact#`, `Domicile`, `Blood_Group`, `Date_of_Birth`, `Salary`, `Hiring_Date`, `F_Name`, `cnic#`, `Adress`, `image`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";
            pst=cn.prepareStatement(sql);
            pst.setString(1, Name);
            pst.setString(2, password);
            pst.setString(3, gender);
            pst.setString(4, contact);
            pst.setString(5, domicile);
            pst.setString(6, bgroup);
            pst.setString(7, bdate);
            pst.setString(8, salary);
            pst.setString(9, hdate);
            pst.setString(10, Fname);
            pst.setString(11, cinc);
            pst.setString(12, address);
            pst.setString(13, path);
            pst.execute();
//            st=cn.createStatement();
//            rs=st.executeQuery("SELECT `Emp_ID` FROM employee");
//            rs.next();
            
//            String id=rs.getString(1);
//            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
//        model.addRow(new Object[]{id,Name,Fname,cinc,contact,gender,bdate,hdate,bgroup,address,domicile,password,salary});
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
        JOptionPane.showMessageDialog(null, "Saved");
    }//GEN-LAST:event_jbsaveActionPerformed

    private void rmaleeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmaleeActionPerformed
        // TODO add your handling code here:
        if(rmalee.isSelected())
        {
            gender=rmalee.getText();
            
        }
    }//GEN-LAST:event_rmaleeActionPerformed

    private void rfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfemaleActionPerformed
        // TODO add your handling code here:
        if(rfemale.isSelected())
        {
            gender=rfemale.getText();
           
        }
    }//GEN-LAST:event_rfemaleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
           
            JFileChooser obj = new JFileChooser(new File("C:\\Users\\walee_000\\Downloads"));
            obj.showOpenDialog(this);
            
             path = obj.getSelectedFile().getAbsolutePath();
            limage.setIcon(new ImageIcon(ThisIsANameOfFun(limage, path)));
            tfimage.setText(path);
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        try
        {
        int row=jTable1.getSelectedRow();
        String tclick=(jTable1.getModel().getValueAt(row, 0).toString());
        String sqll="SELECT * from employee where Emp_ID='"+tclick+"' ";
        pst=cn.prepareStatement(sqll);
        rs=pst.executeQuery();
        if(rs.next())
        {
//          String path=  rs.getString("image");
//           format=new ImageIcon(path);
//           limage.setIcon(format);
            String s0=rs.getString("Emp_ID");
                tfupdate.setText(s0);
                String s1=rs.getString("Name");
                tfname.setText(s1);
                String s2=rs.getString("F_Name");
                tffname.setText(s2);
                String s3=rs.getString("cnic#");
                tfcnic.setText(s3);
                String s4=rs.getString("Contact#");
                tfcontact.setText(s4);
//               String s5=rs.getString("Gender");
//             if(rmalee.getText().equals(s5))
//              rmalee.setAction(s5);
//               else if(rfemale.getText().equals(s5))
//               rfemale.doClick();
               Date s6=rs.getDate("Date_of_Birth");
               jdatebd.setDate(s6);

                String s7=rs.getString("Domicile");
                tfdomicile.setText(s7);
                String s8=rs.getString("Adress");
                tfadress.setText(s8);
                 Date s9=rs.getDate("Hiring_Date");
                jdatehd.setDate(s9);
                String s10=rs.getString("E_Password");
                tfpassword.setText(s10);
                String s11=rs.getString("Salary");
                tfsalary.setText(s11);
                String s12=rs.getString("Blood_Group");
                tfbgroup.setText(s12);
                String s13=rs.getString("image");
                limage.setIcon(new ImageIcon(ThisIsANameOfFun(limage, s13)));
                String s14=rs.getString("image");
                tfimage.setText(s14);
        }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void tfupdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfupdateKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
         try
 {
            String sql="SELECT * FROM `employee` WHERE Emp_ID=?";
            pst=cn.prepareStatement(sql);
            pst.setString(1, tfupdate.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String s1=rs.getString("Name");
                tfname.setText(s1);
                String s2=rs.getString("F_Name");
                tffname.setText(s2);
                String s3=rs.getString("cnic#");
                tfcnic.setText(s3);
                String s4=rs.getString("Contact#");
                tfcontact.setText(s4);
//               String s5=rs.getString("Gender");
//              if(rmale.getText().equals(s5))
//               rmale.doClick();
//               else if(rfemale.getText().equals(s5))
//               rfemale.doClick();
               Date s6=rs.getDate("Date_of_Birth");
               jdatebd.setDate(s6);
               
                String s7=rs.getString("Domicile");
                tfdomicile.setText(s7);
                String s8=rs.getString("Adress");
                tfadress.setText(s8);
                 Date s9=rs.getDate("Hiring_Date");
                jdatehd.setDate(s9);
                String s10=rs.getString("E_Password");
                tfpassword.setText(s10);
                String s11=rs.getString("Salary");
                tfsalary.setText(s11);
                String s12=rs.getString("Blood_Group");
                tfbgroup.setText(s12);
                String s13=rs.getString("image");
                limage.setIcon(new ImageIcon(ThisIsANameOfFun(limage, s13)));
                String s14=rs.getString("image");
                tfimage.setText(s14);
            }
 }
                 catch(Exception e)
            
                     {
                         System.out.println(e); 
                     }
        }
    }//GEN-LAST:event_tfupdateKeyPressed

    private void jbupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbupdateActionPerformed
        // TODO add your handling code here:
        Name=tfname.getText();
        Fname=tffname.getText();
        address=tfadress.getText();
        domicile=tfdomicile.getText();
        contact=tfcontact.getText();
        password=tfpassword.getText();
        salary=tfsalary.getText();
        bgroup=tfbgroup.getText();
        cinc=tfcnic.getText();
        hdate=((JTextField)jdatehd.getDateEditor().getUiComponent()).getText();
        
        bdate= ((JTextField)jdatebd.getDateEditor().getUiComponent()).getText();
        try
        {
            
            
            String sql="UPDATE `employee` SET `Name`=?,`E_Password`=?,`Gender`=?,`Contact#`=?,`Domicile`=?,`Blood_Group`=?,`Date_of_Birth`=?,`Salary`=?,`Hiring_Date`=?,`F_Name`=?,`cnic#`=?,`Adress`=?,`image`=? WHERE `Emp_ID`=?";
            pst=cn.prepareStatement(sql);
            
            pst.setString(1, Name);
            pst.setString(2, password);
            pst.setString(3, gender);
            pst.setString(4, contact);
            pst.setString(5, domicile);
            pst.setString(6, bgroup);
            pst.setString(7, bdate);
            pst.setString(8, salary);
            pst.setString(9, hdate);
          
            pst.setString(10, Fname);
            pst.setString(11, cinc);
            pst.setString(12, address);
            
            pst.setString(13, path);
            pst.setString(14, tfupdate.getText());
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"Updated");
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jbupdateActionPerformed

    private void jbdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdeleteActionPerformed
        // TODO add your handling code here:
        try
        {
            String sqll="DELETE FROM `employee` WHERE Emp_id=?";
            pst=cn.prepareStatement(sqll);
            pst.setString(1, tfupdate.getText());
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Deleted");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jbdeleteActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
         try
        {
            
        Statement st=cn.createStatement();
        rs=st.executeQuery("SELECT `Emp_ID`, `Name`, `Gender`, `Contact#`, `Salary` FROM employee");
        DefaultTableModel dt=rtt(rs);
        
        jTable1.setModel(dt);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_formMouseMoved

    private void tfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnameActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tfnameActionPerformed

    private void tffnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tffnameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tffnameActionPerformed

    private void tfcnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcnicActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfcnicActionPerformed

    private void tfcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcontactActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfcontactActionPerformed

    private void tfdomicileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdomicileActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tfdomicileActionPerformed

    private void tfbgroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfbgroupActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfbgroupActionPerformed

    private void tfadressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfadressActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tfadressActionPerformed

    private void tfpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpasswordActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfpasswordActionPerformed

    private void tfsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfsalaryActionPerformed

    private void tfnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnameKeyReleased
        // TODO add your handling code here:
        jp.setValue(8);
    }//GEN-LAST:event_tfnameKeyReleased

    private void tffnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tffnameKeyReleased
        // TODO add your handling code here:
        jp.setValue(15);
    }//GEN-LAST:event_tffnameKeyReleased

    private void tfcnicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcnicKeyReleased
        // TODO add your handling code here:
        jp.setValue(23);
    }//GEN-LAST:event_tfcnicKeyReleased

    private void tfcontactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcontactKeyReleased
        // TODO add your handling code here:
        jp.setValue(31);
    }//GEN-LAST:event_tfcontactKeyReleased

    private void rmaleeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rmaleeMouseClicked
        // TODO add your handling code here:
        jp.setValue(38);
    }//GEN-LAST:event_rmaleeMouseClicked

    private void rfemaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rfemaleMouseClicked
        // TODO add your handling code here:
        jp.setValue(38);
    }//GEN-LAST:event_rfemaleMouseClicked

    private void tfdomicileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdomicileKeyReleased
        // TODO add your handling code here:
        jp.setValue(51);
    }//GEN-LAST:event_tfdomicileKeyReleased

    private void tfbgroupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfbgroupKeyReleased
        // TODO add your handling code here:
        jp.setValue(56);
    }//GEN-LAST:event_tfbgroupKeyReleased

    private void tfadressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfadressKeyReleased
        // TODO add your handling code here:
        jp.setValue(64);
    }//GEN-LAST:event_tfadressKeyReleased

    private void tfpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfpasswordKeyReleased
        // TODO add your handling code here:
        jp.setValue(80);
    }//GEN-LAST:event_tfpasswordKeyReleased

    private void tfsalaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfsalaryKeyReleased
        // TODO add your handling code here:
        jp.setValue(90);
    }//GEN-LAST:event_tfsalaryKeyReleased

    private void jButton1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1KeyReleased

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        jp.setValue(100);
    }//GEN-LAST:event_jButton1MousePressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Admin ad=new Admin();
        ad.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void tfcnicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcnicKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
          evt.consume();
        }
    }//GEN-LAST:event_tfcnicKeyTyped

    private void tfcontactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcontactKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
          evt.consume();
        }
    }//GEN-LAST:event_tfcontactKeyTyped

    private void tfsalaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfsalaryKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
          evt.consume();
        }
    }//GEN-LAST:event_tfsalaryKeyTyped

    private void tfupdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfupdateKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
          evt.consume();
        }
    }//GEN-LAST:event_tfupdateKeyTyped

    private void tfnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnameKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) || c==KeyEvent.VK_SPACE))
        {
            getToolkit().beep();
          evt.consume();
        }
    }//GEN-LAST:event_tfnameKeyTyped

    private void tffnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tffnameKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) || c==KeyEvent.VK_SPACE))
        {
            getToolkit().beep();
          evt.consume();
        }
    }//GEN-LAST:event_tffnameKeyTyped

    private void tfdomicileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdomicileKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) || c==KeyEvent.VK_SPACE))
        {
            getToolkit().beep();
          evt.consume();
        }
    }//GEN-LAST:event_tfdomicileKeyTyped

    private void tfbgroupKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfbgroupKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) || c==KeyEvent.VK_SPACE))
        {
            getToolkit().beep();
          evt.consume();
        }
    }//GEN-LAST:event_tfbgroupKeyTyped

    private void tfadressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfadressKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) || c==KeyEvent.VK_SPACE))
        {
            getToolkit().beep();
          evt.consume();
        }
    }//GEN-LAST:event_tfadressKeyTyped

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        try
        {
            String sqll="DELETE FROM `employee` WHERE Emp_id=?";
            pst=cn.prepareStatement(sqll);
            pst.setString(1, tfupdate.getText());
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Deleted");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeForm().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbdelete;
    private javax.swing.JButton jbsave;
    private javax.swing.JButton jbupdate;
    private com.toedter.calendar.JDateChooser jdatebd;
    private com.toedter.calendar.JDateChooser jdatehd;
    private javax.swing.JProgressBar jp;
    private javax.swing.JLabel limage;
    private javax.swing.JRadioButton rfemale;
    private javax.swing.JRadioButton rmalee;
    private javax.swing.JScrollPane showtable;
    private javax.swing.JTextField tfadress;
    private javax.swing.JTextField tfbgroup;
    private javax.swing.JTextField tfcnic;
    private javax.swing.JTextField tfcontact;
    private javax.swing.JTextField tfdomicile;
    private javax.swing.JTextField tffname;
    private javax.swing.JTextField tfimage;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tfpassword;
    private javax.swing.JTextField tfsalary;
    private javax.swing.JTextField tfupdate;
    // End of variables declaration//GEN-END:variables

    String filename;
    int s=0;
    byte[] person_image=null;
    private ImageIcon format=null;
    
}