/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package departmentalstore;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author walee_000
 */
public class ItemForm extends javax.swing.JFrame {
    String code,name,quantity,price,type,date,kg,tquantity,stock;
    int sprice,priceint,pstock;
    Connection cn;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * Creates new form ItemForm
     */
    public ItemForm() {
        initComponents();
        kg="";
        try
        {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            cn= DriverManager.getConnection("jdbc:mysql://localhost:3306/departmental_store", "root", "");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfcode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfquantity = new javax.swing.JTextField();
        jbsave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfprice = new javax.swing.JTextField();
        ctype = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ckg = new javax.swing.JCheckBox();
        jbupdate = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jdate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ItemCode:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 23, -1, -1));

        tfcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcodeActionPerformed(evt);
            }
        });
        tfcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfcodeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfcodeKeyReleased(evt);
            }
        });
        getContentPane().add(tfcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 20, 101, -1));

        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, -1, -1));

        tfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnameActionPerformed(evt);
            }
        });
        tfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfnameKeyReleased(evt);
            }
        });
        getContentPane().add(tfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 51, 236, -1));

        jLabel3.setText("Quantity:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, -1, -1));

        tfquantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfquantityKeyTyped(evt);
            }
        });
        getContentPane().add(tfquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 82, 155, -1));

        jbsave.setIcon(new javax.swing.ImageIcon("D:\\Smester#4\\SE2\\project\\save.jpg")); // NOI18N
        jbsave.setText("Save");
        jbsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsaveActionPerformed(evt);
            }
        });
        getContentPane().add(jbsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 231, -1, -1));

        jLabel4.setText("Price(PI):");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 116, -1, -1));

        tfprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfpriceKeyTyped(evt);
            }
        });
        getContentPane().add(tfprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 113, 236, -1));

        ctype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".......", "Glossary", "Drink", "Electrical", "Bakery", "Cosmatics", "Food", "Drugs/Medicines" }));
        getContentPane().add(ctype, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 144, 236, -1));

        jLabel5.setText("Type:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel6.setText("Date:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 179, -1, -1));

        ckg.setText("KG/Liter");
        ckg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckgActionPerformed(evt);
            }
        });
        getContentPane().add(ckg, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 81, -1, -1));

        jbupdate.setIcon(new javax.swing.ImageIcon("D:\\Smester#4\\SE2\\project\\UPDATE.jpg")); // NOI18N
        jbupdate.setText("Update");
        jbupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbupdateActionPerformed(evt);
            }
        });
        getContentPane().add(jbupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 230, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 51, 0));
        jLabel7.setText("Enter ItemCode to Search");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 23, -1, -1));

        jdate.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 179, 236, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\Smester#4\\SE2\\project\\light_cool_abstract_wallpapers_hd_57_dekstop_wus.jpg")); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 340, 300));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("Close");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Main Page");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnameActionPerformed

    private void jbsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsaveActionPerformed
        // TODO add your handling code here:
       
        try
        {
             code=tfcode.getText();
        name=tfname.getText();
        quantity=tfquantity.getText();
        price=tfprice.getText();
        type=ctype.getSelectedItem().toString();
        date=((JTextField)jdate.getDateEditor().getUiComponent()).getText();
        tquantity=quantity+kg;
            String sql="INSERT INTO `productdetails`(`Date`,`P_id`, `P_Name`, `P_type`, `P_price`, `Total_Stock`) VALUES (?,?,?,?,?,?)";
            pst=cn.prepareStatement(sql);
            pst.setString(1, date);
            pst.setString(2, code);
            pst.setString(3, name);
            pst.setString(4, type);
            pst.setString(5, price);
            pst.setString(6, tquantity);
            pst.execute();
         
           /*
            String sqll1="SELECT * FROM purchase WHERE Product_id=?";
            pst=cn.prepareStatement(sqll1);
            pst.setString(1, code);
            rs=pst.executeQuery();
            if(rs.next())
            {
            
            
           String sqll="UPDATE `purchase` SET `Stock`=?,`Total_Price`=? WHERE Product_id=? ";
            pst=cn.prepareStatement(sqll);
            int tquantity_int=Integer.parseInt(tquantity);
            pstock=pstock+tquantity_int;
            String ps=String.valueOf(pstock);
            priceint=Integer.parseInt(price);
            sprice=pstock*priceint;
            String sp=String.valueOf(sprice);
            pst.setString(1, ps);
            pst.setString(2, sp);
            pst.setString(3, code);
            
            pst.execute();
            }
            else
            {
            */
            
            int tquantity_int=Integer.parseInt(tquantity);
            //pstock=pstock+tquantity_int;
            //String ps=String.valueOf(pstock);
            priceint=Integer.parseInt(price);
            sprice=tquantity_int*priceint;
            String sp=String.valueOf(sprice);
            
                String sqll2="INSERT INTO `purchase`(`Product_id`, `Name`, `Stock`, `Total_Price`,`Date`) VALUES (?,?,?,?,?)";
            pst=cn.prepareStatement(sqll2);
            pst.setString(1, code);
            pst.setString(2, name);
            pst.setString(3, tquantity);
            
            pst.setString(4, sp);
            pst.setString(5, date);
            pst.execute();
            
            
            JOptionPane.showMessageDialog(null,"Saved");
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jbsaveActionPerformed

    private void tfcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcodeActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_tfcodeActionPerformed

    private void tfcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcodeKeyReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_tfcodeKeyReleased

    private void tfnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnameKeyReleased
        // TODO add your handling code here:
         
    }//GEN-LAST:event_tfnameKeyReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        EmployeePanel ep=new EmployeePanel();
        ep.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void ckgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckgActionPerformed
        // TODO add your handling code here:
        if(ckg.isSelected())
        {
            kg=ckg.getText();
        }
    }//GEN-LAST:event_ckgActionPerformed

    private void tfquantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfquantityKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
          evt.consume();
        }
    }//GEN-LAST:event_tfquantityKeyTyped

    private void tfpriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfpriceKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
          evt.consume();
        }
    }//GEN-LAST:event_tfpriceKeyTyped

    private void tfcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcodeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
         try
            {
                String sqll="SELECT * FROM `productdetails` WHERE P_id=?";
            pst=cn.prepareStatement(sqll);
            pst.setString(1, tfcode.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String s1=rs.getString("P_Name");
                tfname.setText(s1);
                String s2=rs.getString("Total_Stock");
                tfquantity.setText(s2);
                String s3=rs.getString("P_price");
                tfprice.setText(s3);
                Date s4=rs.getDate("Date");
                jdate.setDate(s4);
                String s5=rs.getString("P_type");
                ctype.setSelectedItem(s5);
                
                
            }
            }
            
    
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_tfcodeKeyPressed

    private void jbupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbupdateActionPerformed
        // TODO add your handling code here:
         try
        {
             code=tfcode.getText();
        name=tfname.getText();
        quantity=tfquantity.getText();
        price=tfprice.getText();
        type=ctype.getSelectedItem().toString();
        date=((JTextField)jdate.getDateEditor().getUiComponent()).getText();
        tquantity=quantity+kg;
            String sql="UPDATE `productdetails` SET `Date`=?,`P_Name`=?,`P_type`=?,`P_price`=?,`Total_Stock`=? WHERE P_id=?";
            pst=cn.prepareStatement(sql);
            pst.setString(1, date);
            
            pst.setString(2, name);
            pst.setString(3, type);
            pst.setString(4, price);
            pst.setString(5, tquantity);
            pst.setString(6, code);
            pst.execute();
            
            int tquantity_int=Integer.parseInt(tquantity);
             priceint=Integer.parseInt(price);
            sprice=tquantity_int*priceint;
            String sp=String.valueOf(sprice);
            String sql2="UPDATE `purchase` SET `Name`=?,`Stock`=?,`Total_Price`=? WHERE `Product_id`=?";
            pst=cn.prepareStatement(sql2);
            pst.setString(1, name);
            pst.setString(2, tquantity);
            pst.setString(3, sp);
            pst.setString(4, code);
            pst.execute();
            
         
            JOptionPane.showMessageDialog(null, "Updated");
        }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null, e);
         }
    }//GEN-LAST:event_jbupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ckg;
    private javax.swing.JComboBox ctype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JButton jbsave;
    private javax.swing.JButton jbupdate;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JTextField tfcode;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tfprice;
    private javax.swing.JTextField tfquantity;
    // End of variables declaration//GEN-END:variables
}
