/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package departmentalstore;
import static departmentalstore.Admin.limagee;
import static departmentalstore.EmployeePanel.limage;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author walee_000
 */
public class Login extends javax.swing.JFrame {
    String name,password;
    Connection cn;
    Statement st;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        try
        {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            cn= DriverManager.getConnection("jdbc:mysql://localhost:3306/departmental_store", "root", "");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pf = new javax.swing.JPasswordField();
        jblogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tgadmin = new javax.swing.JToggleButton();
        tgemployee = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 455, -1, -1));
        getContentPane().add(tfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 452, 290, -1));

        jLabel2.setText("Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 486, -1, -1));
        getContentPane().add(pf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 483, 290, -1));

        jblogin.setIcon(new javax.swing.ImageIcon("D:\\Smester#4\\SE2\\project\\1LOGIN.jpg")); // NOI18N
        jblogin.setText("Login");
        jblogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbloginMouseMoved(evt);
            }
        });
        jblogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbloginActionPerformed(evt);
            }
        });
        jblogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbloginKeyPressed(evt);
            }
        });
        getContentPane().add(jblogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 459, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Smester#4\\SE2\\project\\macy-department-store-has-refused-turn-over-prosecutors-the-27599.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        buttonGroup1.add(tgadmin);
        tgadmin.setIcon(new javax.swing.ImageIcon("D:\\Smester#4\\SE2\\project\\admin1.jpg")); // NOI18N
        tgadmin.setText("Admin");
        getContentPane().add(tgadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 401, -1, -1));

        buttonGroup1.add(tgemployee);
        tgemployee.setIcon(new javax.swing.ImageIcon("D:\\Smester#4\\SE2\\project\\employee1.jpg")); // NOI18N
        tgemployee.setText("Employee");
        getContentPane().add(tgemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 401, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Smester#4\\SE2\\project\\light_cool_abstract_wallpapers_hd_57_dekstop_wus.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 570, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private BufferedImage ThisIsANameOfFun(JLabel label, String address) throws IOException {
       
            BufferedImage buffer = new BufferedImage(label.getWidth(), label.getHeight(), BufferedImage.TYPE_INT_ARGB);
            Graphics2D g = buffer.createGraphics();          
            Image img = ImageIO.read(new File(address));           
            g.drawImage(img, 0, 0, label.getWidth(), label.getHeight(), null);           
            g.dispose();      
        return buffer;
    }
    private void jbloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbloginActionPerformed
        // TODO add your handling code here:
        name=tfname.getText();
      //  password=String.valueOf(pf.getPassword());
        password=pf.getText();
        if(tgadmin.isSelected())
        {
            try
            {
                
                
                String sql="SELECT * FROM login WHERE u_id=? and password=? ";
                pst=cn.prepareStatement(sql);
                pst.setString(1, name);
                pst.setString(2, password);
                rs=pst.executeQuery();
                if(rs.next())
                {
                    JOptionPane.showMessageDialog(null,"Login Success");
                    Admin ad=new Admin();
                    Admin.lname.setText(this.name);
                  // String s1=rs.getString("a_image");
               // Admin.limagee.setIcon(new ImageIcon(ThisIsANameOfFun(limagee, s1)));
                    ad.setVisible(true);
                    this.setVisible(false);
                }
                 else
                {
                    JOptionPane.showMessageDialog(null, "Invalid");
                }
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
        if(tgemployee.isSelected())
        {
            try
            {
                
                String sql="SELECT * FROM employee WHERE Name=? and E_Password=? ";
                
                pst=cn.prepareStatement(sql);
                pst.setString(1, name);
                pst.setString(2, password);
                rs=pst.executeQuery();
                if(rs.next())
                {
//                String un=rs.getString(2);
//                String pass=rs.getString(3);
                
                
                    JOptionPane.showMessageDialog(null,"Login Success");
                    EmployeePanel ep=new EmployeePanel();
                  //  String s13=rs.getString("image");
               // EmployeePanel.limage.setIcon(new ImageIcon(ThisIsANameOfFun(limage, s13)));
                    EmployeePanel.lname.setText(this.name);
                    ep.setVisible(true);
                    this.setVisible(false);
                }
                 else
                {
                    JOptionPane.showMessageDialog(null, "Invalid");
                }
            }
        
            catch(Exception e)
            {
                System.out.println(e);
            }
            
            
        }
    }//GEN-LAST:event_jbloginActionPerformed

    private void jbloginMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbloginMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbloginMouseMoved

    private void jbloginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbloginKeyPressed
        // TODO add your handling code here:
         name=tfname.getText();
        password=String.valueOf(pf.getPassword());
        if(tgadmin.isSelected())
        {
            try
            {
                
                st=cn.createStatement();
                rs=st.executeQuery("SELECT * FROM login");
                rs.next();
                
                String un=rs.getString(1);
                String pass=rs.getString(2);
                if(name.equals(un)&&password.equals(pass))
                {
                    JOptionPane.showMessageDialog(null,"Login Success");
                    Admin ad=new Admin();
                    ad.setVisible(true);
                    this.setVisible(false);
                }
                 else
                {
                    JOptionPane.showMessageDialog(null, "Invalid");
                }
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
        if(tgemployee.isSelected())
        {
            try
            {
                
                st=cn.createStatement();
                rs=st.executeQuery("SELECT * FROM employee");
                rs.next();
                
                String un=rs.getString(2);
                String pass=rs.getString(3);
                if(name.equals(un)&&password.equals(pass))
                {
                    JOptionPane.showMessageDialog(null,"Login Success");
                    EmployeePanel ep=new EmployeePanel();
                    ep.setVisible(true);
                }
                 else
                {
                    JOptionPane.showMessageDialog(null, "Invalid");
                }
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
            
            
        }
    }//GEN-LAST:event_jbloginKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jblogin;
    private javax.swing.JPasswordField pf;
    private javax.swing.JTextField tfname;
    private javax.swing.JToggleButton tgadmin;
    private javax.swing.JToggleButton tgemployee;
    // End of variables declaration//GEN-END:variables
}
