/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package departmentalstore;

import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author walee_000
 */
public class MakeBill extends javax.swing.JFrame {
    String productid,name,quantity,price,date,apaid,jdatec,cname,ccontact,eid;
    int totalprice,balance,totalproducts,totalamount;
    Connection cn;
    Statement st;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form MakeBill
     */
    public MakeBill() {
        initComponents();
        try
        {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/departmental_store","root","");
        }
        catch(Exception e)
        {
          JOptionPane.showMessageDialog(null,e);  
        }
    }
////private DefaultTableModel rtt(ResultSet rs){
////    try{
////            DefaultTableModel dtm = new DefaultTableModel();
////            ResultSetMetaData meta = rs.getMetaData();
////            int col = meta.getColumnCount();
//// 
////            rs.last();
////            int row = rs.getRow();
////            rs.beforeFirst();
//// 
////            Object[] rowData = new Object[col];
////            Object[] colData = new Object[col];
//// 
////            for (int i=0;i<col;i++){
////                colData[i] = meta.getColumnLabel(i+1);
////            }
//// 
////            dtm.setColumnIdentifiers(colData);
//// 
////            for (int i=0;i<row;i++){
////                rs.next();
////                for (int j=0;j<col;j++){
////                    rowData[j] = rs.getString(j+1);
////                }
////                dtm.addRow(rowData);
////            }
//// 
////            return dtm;
////    } catch (Exception ex){
////        JOptionPane.showMessageDialog(null, "ResultSet to TableModel Converter : "+ex.getMessage());
////        return null;
////    }
////}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfcn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfcontact = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfeid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jdate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        tfpid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfquantity = new javax.swing.JTextField();
        jbenter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rtable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tftp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfap = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfb = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfprice = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setText("Customer Name:");

        tfcn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfcnKeyTyped(evt);
            }
        });

        jLabel2.setText("Contact#:");

        tfcontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfcontactKeyTyped(evt);
            }
        });

        jLabel3.setText("Employee ID:");

        tfeid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfeidKeyTyped(evt);
            }
        });

        jLabel4.setText("Date:");

        jdate.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfcn)
                    .addComponent(tfcontact, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfeid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfcn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfeid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tfcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(jdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 11, -1, -1));

        jLabel5.setText("Product ID:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 96, -1, -1));

        tfpid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfpidKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfpidKeyTyped(evt);
            }
        });
        getContentPane().add(tfpid, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 93, 76, -1));

        jLabel6.setText("Name:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 96, -1, -1));

        tfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfnameKeyTyped(evt);
            }
        });
        getContentPane().add(tfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 93, 118, -1));

        jLabel7.setText("Quantity:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 96, -1, -1));

        tfquantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfquantityKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfquantityKeyTyped(evt);
            }
        });
        getContentPane().add(tfquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 93, 77, -1));

        jbenter.setText("Enter");
        jbenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbenterActionPerformed(evt);
            }
        });
        jbenter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbenterKeyPressed(evt);
            }
        });
        getContentPane().add(jbenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 92, -1, -1));

        rtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Price", "Quantity", "Total Price"
            }
        ));
        jScrollPane1.setViewportView(rtable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 126, 608, 201));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setText("Total Products:");

        jLabel9.setText("Total Amount:");

        jLabel10.setText("Amount Paid:");

        tfap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        tfap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfapKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfapKeyTyped(evt);
            }
        });

        jLabel11.setText("Balance:");

        tfb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tftp, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfta, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfap, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfb, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tftp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tfta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tfap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tfb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 333, -1, -1));

        jLabel12.setText("Price:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 96, -1, -1));

        tfprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfpriceKeyTyped(evt);
            }
        });
        getContentPane().add(tfprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 93, 85, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon("D:\\Smester#4\\SE2\\project\\light_cool_abstract_wallpapers_hd_57_dekstop_wus.jpg")); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 640, 410));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("Close");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Main Page");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbenterActionPerformed
        // TODO add your handling code here:
        productid=tfpid.getText();
        name=tfname.getText();
        quantity=tfquantity.getText();
        
        price=tfprice.getText();
          int price_int=Integer.parseInt(price);
        int q_int=Integer.parseInt(quantity);
        totalprice=price_int*q_int;
        String tp=String.valueOf(totalprice);
        
        jdatec=((JTextField)jdate.getDateEditor().getUiComponent()).getText();
        
        
        try
        {
          
            
        String sql="INSERT INTO `bill`(`Date`, `P_id`, `P_name`, `Quantity`, `unit_price`, `T_price`) VALUES (?,?,?,?,?,?)";
        pst=cn.prepareStatement(sql);
        pst.setString(1, jdatec);
        pst.setString(2, productid);
        pst.setString(3, name);
        pst.setString(4, quantity);
        pst.setString(5, price);
        pst.setString(6, tp);
        pst.execute();
        
        String sql2="SELECT * FROM `sale` WHERE `Product_id`=?";
        pst=cn.prepareStatement(sql2);
        pst.setString(1, productid);
        rs=pst.executeQuery();
        if(rs.next())
        {
            
           String s1= rs.getString("Quantity"); 
        int s1_int = Integer.parseInt(s1);
        int ts1_int=q_int+s1_int;
        String ts1=String.valueOf(ts1_int);
        String s2=rs.getString("Price");
        int s2_int=Integer.parseInt(s2);
        int ts2_int=totalprice+s2_int;
        String ts2=String.valueOf(ts2_int);
            
            
            
            
            
        String sql3="UPDATE `sale` SET `Date`=?,`Name`=?,`Quantity`=?,`Price`=? WHERE `Product_id`=?";
        pst=cn.prepareStatement(sql3);
        pst.setString(1, jdatec);
        pst.setString(2, name);
        pst.setString(3, ts1);
        
        pst.setString(4, ts2);
        pst.setString(5, productid);
        pst.execute();
        }
        else
        {
            String sql1="INSERT INTO `sale`(`Date`, `Product_id`, `Name`, `Quantity`, `Price`) VALUES (?,?,?,?,?)";
        pst=cn.prepareStatement(sql1);
        pst.setString(1, jdatec);
        pst.setString(2, productid);
        pst.setString(3, name);
        pst.setString(4, quantity);
        pst.setString(5, tp);
        pst.execute();
        }
        
        String sql5="SELECT * FROM `productdetails` WHERE `P_id`=?";
        pst=cn.prepareStatement(sql5);
        pst.setString(1, productid);
        rs=pst.executeQuery();
        if(rs.next())
        {
          String s3= rs.getString("Total_Stock"); 
        int s3_int = Integer.parseInt(s3);
        int ts3_int=s3_int-q_int;
        String ts3=String.valueOf(ts3_int);
        
        
        String sql6="UPDATE `productdetails` SET `Date`=?,`Total_Stock`=? WHERE `P_id`=?";
        pst=cn.prepareStatement(sql6);
        pst.setString(1, jdatec);
        pst.setString(2, ts3);
        pst.setString(3, productid);   
        pst.execute();
        }
        
        
        
        
        
        
        
        
        
        
        
        DefaultTableModel model=(DefaultTableModel)rtable.getModel();
        model.addRow(new Object[]{productid,name,price,quantity,totalprice});
        
        for(int i=1;i<2;i++)
        {
           totalproducts+=1;
           String tpp=String.valueOf(totalproducts);
           tftp.setText(tpp);
          totalamount+=totalprice;
          String taa=String.valueOf(totalamount);
          tfta.setText(taa);
        }
        
     
        cname=tfcn.getText();
        ccontact=tfcontact.getText();
        eid=tfeid.getText();
        String sql7="INSERT INTO `customer`(`C_name`, `C_contact`, `Employee_id`,`Date`) VALUES (?,?,?,?)";
        pst=cn.prepareStatement(sql7);
        pst.setString(1, cname);
        pst.setString(2, ccontact);
        pst.setString(3, eid);
        pst.setString(4, jdatec);
        pst.execute();
        
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jbenterActionPerformed

    private void tfapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfapKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            try
        {
        apaid=tftp.getText();
        int apaid_int=Integer.parseInt(apaid);
        balance=apaid_int-totalamount;
        String b=String.valueOf(balance);
        tfb.setText(b);
        }
        catch(Exception e)
        {
            
        }
            
        }
    }//GEN-LAST:event_tfapKeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        EmployeePanel ep=new EmployeePanel();
        ep.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void tfnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnameKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) || c==KeyEvent.VK_SPACE))
        {
            getToolkit().beep();
          evt.consume();
        }
    }//GEN-LAST:event_tfnameKeyTyped

    private void tfpriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfpriceKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) ))
        {
            getToolkit().beep();
          evt.consume();
        }
    }//GEN-LAST:event_tfpriceKeyTyped

    private void tfquantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfquantityKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
          evt.consume();
        }
    }//GEN-LAST:event_tfquantityKeyTyped

    private void tfcontactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcontactKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
          evt.consume();
        }
    }//GEN-LAST:event_tfcontactKeyTyped

    private void tfcnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcnKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) || c==KeyEvent.VK_SPACE))
        {
            getToolkit().beep();
          evt.consume();
        }
    }//GEN-LAST:event_tfcnKeyTyped

    private void tfeidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfeidKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
          evt.consume();
        }
    }//GEN-LAST:event_tfeidKeyTyped

    private void tfapKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfapKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
          evt.consume();
        }
    }//GEN-LAST:event_tfapKeyTyped

    private void jbenterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbenterKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbenterKeyPressed

    private void tfquantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfquantityKeyPressed
        // TODO add your handling code here:
       /*
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
        productid=tfpid.getText();
        name=tfname.getText();
        quantity=tfquantity.getText();
        
        price=tfprice.getText();
          int price_int=Integer.parseInt(price);
        int q_int=Integer.parseInt(quantity);
        totalprice=price_int*q_int;
        String tp=String.valueOf(totalprice);
        try
        {
          
            
        String sql="INSERT INTO `bill`(`Date`, `P_id`, `P_name`, `Quantity`, `unit_price`, `T_price`) VALUES (?,?,?,?,?,?)";
        pst=cn.prepareStatement(sql);
        pst.setString(1, date);
        pst.setString(2, productid);
        pst.setString(3, name);
        pst.setString(4, quantity);
        pst.setString(5, price);
        pst.setString(6, tp);
        pst.execute();
        
        
        
        String sql1="INSERT INTO `sale`(`Date`, `Product_id`, `Name`, `Quantity`, `Price`) VALUES (?,?,?,?,?)";
        pst=cn.prepareStatement(sql1);
        pst.setString(1, date);
        pst.setString(2, productid);
        pst.setString(3, name);
        pst.setString(4, quantity);
        pst.setString(5, tp);
        pst.execute();
      
        
        DefaultTableModel model=(DefaultTableModel)rtable.getModel();
        model.addRow(new Object[]{productid,name,price,quantity,totalprice});
        
        for(int i=1;i<2;i++)
        {
           totalproducts+=1;
           String tpp=String.valueOf(totalproducts);
           tftp.setText(tpp);
          totalamount+=totalprice;
          String taa=String.valueOf(totalamount);
          tfta.setText(taa);
        }
        
        
        
        String sql13="SELECT * FROM `productdetails`";
        pst=cn.prepareStatement(sql13);
        rs=pst.executeQuery();
        rs.next();
        String countquantity=rs.getString("`Total_Stock`");
        int c_q_int=Integer.parseInt(countquantity);
       
        c_q_int=c_q_int-q_int;
        String qnew=String.valueOf(c_q_int);
        
        String sql2="UPDATE `productdetails` SET `Total_Stock`=? WHERE P_id=?";
        pst=cn.prepareStatement(sql2);
        pst.setString(1, qnew);
        pst.setString(2, productid);
        pst.executeUpdate();
        
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        }
*/
    }//GEN-LAST:event_tfquantityKeyPressed

    private void tfpidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfpidKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tfpidKeyTyped

    private void tfpidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfpidKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
        try
        {
         String sql8= "SELECT * FROM `productdetails` WHERE `P_id`=?";
         pst=cn.prepareStatement(sql8);
         pst.setString(1, tfpid.getText());
         rs=pst.executeQuery();
         if(rs.next())
         {
             String s9=rs.getString("P_price");
             tfprice.setText(s9);
             String s10=rs.getString("P_Name");
             tfname.setText(s10);
         }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_tfpidKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakeBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbenter;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JTable rtable;
    private javax.swing.JTextField tfap;
    private javax.swing.JTextField tfb;
    private javax.swing.JTextField tfcn;
    private javax.swing.JTextField tfcontact;
    private javax.swing.JTextField tfeid;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tfpid;
    private javax.swing.JTextField tfprice;
    private javax.swing.JTextField tfquantity;
    private javax.swing.JTextField tfta;
    private javax.swing.JTextField tftp;
    // End of variables declaration//GEN-END:variables
}
